lab-13/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :m_threads
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

lab-13/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

lab-13/app/models/m_thread.rb
class MThread < ApplicationRecord
    # Relationship with User
  belongs_to :user
  # Relationship with Posts
  has_many :posts, dependent: :destroy
end

lab-13/app/models/post.rb
class Post < ApplicationRecord
  # Relationship with MThread
  belongs_to :m_thread
  # Relationship with User
  belongs_to :user
end

lab-13/app/models/user.rb
class User < ApplicationRecord
  # Relationship with MThreads
  has_many :m_threads, foreign_key: :user_id, dependent: :destroy
  # Relationship with Posts
  has_many :posts, dependent: :destroy
end

lab-13/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lab-13/app/controllers/m_threads_controller.rb
class MThreadsController < ApplicationController
  before_action :set_m_thread, only: %i[ show edit update destroy ]

  # GET /m_threads or /m_threads.json
  def index
    @m_threads = MThread.all
  end

  # GET /m_threads/1 or /m_threads/1.json
  def show
  end

  # GET /m_threads/new
  def new
    @m_thread = MThread.new
  end

  # GET /m_threads/1/edit
  def edit
  end

  # POST /m_threads or /m_threads.json
  def create
    @m_thread = MThread.new(m_thread_params)

    respond_to do |format|
      if @m_thread.save
        format.html { redirect_to m_thread_url(@m_thread), notice: "M thread was successfully created." }
        format.json { render :show, status: :created, location: @m_thread }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @m_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /m_threads/1 or /m_threads/1.json
  def update
    respond_to do |format|
      if @m_thread.update(m_thread_params)
        format.html { redirect_to m_thread_url(@m_thread), notice: "M thread was successfully updated." }
        format.json { render :show, status: :ok, location: @m_thread }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @m_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /m_threads/1 or /m_threads/1.json
  def destroy
    @m_thread.destroy!

    respond_to do |format|
      format.html { redirect_to m_threads_url, notice: "M thread was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_m_thread
      @m_thread = MThread.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def m_thread_params
      params.require(:m_thread).permit(:title, :created_by)
    end
end

lab-13/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:thread_id, :text, :user_id)
    end
end

lab-13/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :name, :bio)
    end
end

lab-13/app/helpers/application_helper.rb
module ApplicationHelper
end

lab-13/app/helpers/m_threads_helper.rb
module MThreadsHelper
end

lab-13/app/helpers/posts_helper.rb
module PostsHelper
end

lab-13/app/helpers/users_helper.rb
module UsersHelper
end

lab-13/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab13</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab-13/app/views/m_threads/_form.html.erb
<%= form_with(model: m_thread) do |form| %>
  <% if m_thread.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(m_thread.errors.count, "error") %> prohibited this m_thread from being saved:</h2>

      <ul>
        <% m_thread.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :created_by, style: "display: block" %>
    <%= form.number_field :created_by %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

lab-13/app/views/m_threads/_m_thread.html.erb
<div id="<%= dom_id m_thread %>">
  <p>
    <strong>Title:</strong>
    <%= m_thread.title %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= m_thread.created_by %>
  </p>

</div>

lab-13/app/views/m_threads/edit.html.erb
<h1>Editing m thread</h1>

<%= render "form", m_thread: @m_thread %>

<br>

<div>
  <%= link_to "Show this m thread", @m_thread %> |
  <%= link_to "Back to m threads", m_threads_path %>
</div>

lab-13/app/views/m_threads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>M threads</h1>

<div id="m_threads">
  <% @m_threads.each do |m_thread| %>
    <%= render m_thread %>
    <p>
      <%= link_to "Show this m thread", m_thread %>
    </p>
  <% end %>
</div>

<%= link_to "New m thread", new_m_thread_path %>

lab-13/app/views/m_threads/new.html.erb
<h1>New m thread</h1>

<%= render "form", m_thread: @m_thread %>

<br>

<div>
  <%= link_to "Back to m threads", m_threads_path %>
</div>

lab-13/app/views/m_threads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @m_thread %>

<div>
  <%= link_to "Edit this m thread", edit_m_thread_path(@m_thread) %> |
  <%= link_to "Back to m threads", m_threads_path %>

  <%= button_to "Destroy this m thread", @m_thread, method: :delete %>
</div>

lab-13/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :thread_id, style: "display: block" %>
    <%= form.text_field :thread_id %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

lab-13/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Thread:</strong>
    <%= post.thread_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= post.text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

lab-13/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

lab-13/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

lab-13/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

lab-13/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

lab-13/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

lab-13/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= user.bio %>
  </p>

</div>

lab-13/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

lab-13/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

lab-13/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

lab-13/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>